### ISSUE TITLE
Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by AhmedWagdi1** [rameshg87/timewarrior-aggregate#2]
Thanks for the great .. am getting this error when I run `timew aggregate :day` for the first time after getting the binary and moving it to the extensions folder for timwe
```
/home/ahmed/.timewarrior/extensions/aggregate: 1: Syntax error: ")" unexpected
'/home/ahmed/.timewarrior/extensions/aggregate' returned 2 without producing output.

```

**Comment by rameshg87** [comment]
Hello, I want to check which operating system you are trying this on. Is it linux? The binary uploaded in the release page https://github.com/rameshg87/timewarrior-aggregate/releases/tag/0.1 is for MAC OS. Have you built the binary from source if you are using a different operating system?

**Comment by AhmedWagdi1** [comment]
Hello , thanks for your replay , yes am using Linux .. i didn't know the binary is for MAC OS .. i will try to build it from source and will let you know everything goes fine and close the issue .. thank you

**Comment by AhmedWagdi1** [comment]
Build from source using `Rust` and it works as expected , closing this issue
